workflows:
  - "no_dedup"
  - "with_dedup"

# processors used for each call of the rad-seq-stacks workflow
# call the snakemake workflow with twice this amount
cores_per_subworkflow: 3

# locus coverage threshold for plots
plotting_threshold: 100

ddrage:
  loci:
    10000
  individuals:
    # max number possible with standard BC set
    24
  output_prefix:
    "ddrage_testdata"
  ds_name:
    "testdata"
  hrl_number:
    # default 0.05
    0.05
  prob_ID:
    # default: 0.1
    0.1
  prob_het:
    # default: 0.5
    0.5
  event_probs:
    #--event-probabilities 0.9 0.05 0.05 common, dropout, mut
    "0.9 0.05 0.05"
  prob_seq_error:
    # Default: 0.01
    0.01
