# processors used for each call of the rad-seq-stacks workflow
# call the snakemake workflow with twice this amount
cores_per_subworkflow: 3

# locus coverage thresholds for plots
plotting_thresholds:
  - 50
  - 100
  - 1000

workflows:
  - "no_dedup"
  - "with_dedup"
