# define individuals and sequencing units
individuals: individuals.tsv
units: units.tsv

# define the used restriction enzymes
restriction-enzyme:
  p5:
    name: NsiI
    residue-len: 5
  p7:
    name: csp6I
    residue-len: 3

# DBR/UMI handling
umi:
  # length of DBR/UMI
  len: 13
  # maximum hamming distance of UMI to be considered a duplicate
  max_dist: 1
  # maximum hamming distance of read sequence to be considered a duplicate
  max_seq_dist: 8

reads:
  # Expected read length.
  length: 120
  # Spacer sequence to join paired end reads.
  join_seq: NNNNN
  # Read handling mode. This parameter is used to specify
  # input files for ustacks, via the force_same_length rule and the
  # trim_input function.
  #
  # Currently three modes are supported: ["p5_only", "merged", "concatenated"]
  # 
  # "p5_only" uses only the p5 reads, completely ignoring p7 reads.
  #
  #       reads_1.fq
  #       ----------
  #       [r1_p5]
  #       [r2_p5]
  #       ...
  #
  # "merged" (horizontally) merges p5 and p7 read pairs into one long pseudo-single-end read
  #
  #       reads_1.fq     reads_2.fq      reads.fq
  #       ----------     ----------      --------
  #       [r1_p5]     +  [r1_p7]      =  [r1_p5]+[r1_p7]
  #       [r2_p5]        [r1_p7]         [r2_p5]+[r2_p7]
  #       ...            ...             ...
  #
  # "concatenated" (vertically) appends the p7 reads to the p5 read file.
  #
  #       reads_1.fq     reads_2.fq      reads.fq
  #       ----------     ----------      --------
  #       [r1_p5]     +  [r1_p7]      =  [r1_p5]
  #       [r2_p5]        [r1_p7]         [r2_p5]
  #       ...            ...             ...
  #                                      [r1_p7]
  #                                      [r2_p7]
  #                                      ...
  mode: "p5_only"
  
# parameters for tools used in the pipeline
params:
  stacks:
    # * max_individual_mm: Number of mismatches allowed between stacks (M)
    # * max_locus_mm: Number of mismatches allowed between sample loci (n)
    # * min_reads: Minimum depth of coverage required to create a stack (m)
    #
    # Expand or shorted the following list to scan desired parameter spaces:
    - max_individual_mm: 2
      max_locus_mm: 1
      min_reads: 3
    - max_individual_mm: 2
      max_locus_mm: 2
      min_reads: 3
    - max_individual_mm: 3
      max_locus_mm: 3
      min_reads: 3
    - max_individual_mm: 5
      max_locus_mm: 5
      min_reads: 3
    - max_individual_mm: 10
      max_locus_mm: 10
      min_reads: 3
  # command line parameters for gstacks, except -I, -O, -B
  gstacks: ""
  # command line parameters for process_radtags
  # --inline-null         use only p5 barcodes
  # -q                    discard low quality reads
  # -r                    try to rescue barcodes and rad-tags
  # --barcode_dist_1      distance for barcode rescue
  # -D                    capture discarded reads in a file
  # -i gzfastq            input is fqgzip
  # -y gzfastq            output as fqgzip
  process_radtags: "--inline_null -q -r --barcode_dist_1 3 -D -i gzfastq -y gzfastq"
  populations:
    # Desired output formats for the stacks populations script.
    # Possible values are vcf, genepop, fasta, phylip
    output_types:
      - vcf
      - fasta
  kraken:
    # Refer to kraken DB folder, see https://ccb.jhu.edu/software/kraken.
    # Kraken is used to classify reads for possible contaminations.
    # Comment out or leave empty in order to disable kraken.
    db: ../kraken/minikraken_20171013_4GB
