cores_per_subworkflow: 3

plotting_threshold: 100

workflows:
  - "no_dedup"
  - "with_dedup"

# Format: n, M, m
parameter_sets:
  - [2, 2, 3]
  - [5, 5, 3]
  - [3, 2, 3]
  - [4, 3, 3]
  - [16, 15, 3]

ddrage:
  loci:
    100
  individuals:
    # max number possible with standard BC set
    24
  output_prefix:
    "ddrage_testdata"
  ds_name:
    "testdata"
  hrl_number:
    # default 0.05
    0.05
  prob_ID:
    # default: 0.1
    0.1
  prob_het:
    # default: 0.5
    0.5
  event_probs:
    #--event-probabilities common, dropout, mut
    "0.9 0.05 0.05"
  prob_seq_error:
    # Default: 0.01
    0.01
  mutation_probs:
    # only SNPs
    "1 0 0 0 0 0 0"
  read_length:
    100
