cores_per_subworkflow: 3

plotting_threshold: 60


ddrage:
  loci:
    10000
  individuals:
    # max number possible with standard BC set
    24
  output_prefix:
    "ddrage_testdata"
  ds_name:
    "testdata"
  hrl_number:
    # default 0.05
    0.05
  prob_ID:
    # default: 0.1
    0.1
  prob_het:
    # default: 0.5
    0.5
  event_probs:
    #--event-probabilities 0.9 0.05 0.05 common, dropout, mut
    "0.9 0.05 0.05"
  prob_seq_error:
    # Default: 0.01
    0.01
  expected_coverage:
    # simulate low coverage data set ...
    10
  bbd_alpha:
    # with slight left tailing
    3
  bbd_beta:
    # and harder right dropoff
    2
