[package]
name = "stack_sorter"
version = "0.1.0"
authors = ["Henning Timm <henning.timm@tu-dortmund.de>"]
edition = "2018"

[dependencies]
bio = "*"
flate2 = "*"
csv = "*"
indicatif = "*"
itertools = "*"
structopt = "0.3"
