# processors used for each call of the rad-seq-stacks workflow
# call the snakemake workflow with twice this amount
cores_per_subworkflow: 3

# locus coverage threshold for plots
plotting_threshold: 100

ddrage:
  loci:
    10000
  individuals:
    # max number possible with standard BC set
    24
  output_prefix:
    "ddrage_testdata"
  ds_name:
    "testdata"
  hrl_number:
    # default 0.05
    0.05
  prob_ID:
    # default: 0.1
    0.1
  prob_het:
    # default: 0.5
    0.5
  event_probs:
    #--event-probabilities common, dropout, mut
    "0.00 0.00 1.0"
  prob_seq_error:
    # Default: 0.01
    0.02
  expected_coverage:
    30
  diversity:
    # increase diversity to receive more expected diffeing
    # positions between loci
    12
  read_length:
    # increase read length to allow for more mutations in the model
    150
